// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAE_ox6sjF5hpKy_U86PhgiU2hs3OCrN_8',
    appId: '1:854526395916:web:6526aec02d419b446fd029',
    messagingSenderId: '854526395916',
    projectId: 'shriji-garden',
    authDomain: 'shriji-garden.firebaseapp.com',
    storageBucket: 'shriji-garden.firebasestorage.app',
    measurementId: 'G-37WMW85GLT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA5Z9wB0wSx7x9ZH180jUTy0Dts4HKeDBI',
    appId: '1:854526395916:android:7abd79e3f4e702086fd029',
    messagingSenderId: '854526395916',
    projectId: 'shriji-garden',
    storageBucket: 'shriji-garden.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBP8HZ_p5NooPXlAXj4Qtdksvm5iKgnlUY',
    appId: '1:854526395916:ios:86f2410afec6abed6fd029',
    messagingSenderId: '854526395916',
    projectId: 'shriji-garden',
    storageBucket: 'shriji-garden.firebasestorage.app',
    iosBundleId: 'com.shrijigarden.shrijiGardenFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBP8HZ_p5NooPXlAXj4Qtdksvm5iKgnlUY',
    appId: '1:854526395916:ios:86f2410afec6abed6fd029',
    messagingSenderId: '854526395916',
    projectId: 'shriji-garden',
    storageBucket: 'shriji-garden.firebasestorage.app',
    iosBundleId: 'com.shrijigarden.shrijiGardenFlutter',
  );
}
